import { Delius } from "next/font/google";
import "./globals.css";

const delius = Delius({
  weight: "400",
  variable: "--font-delius",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${delius.variable} antialiased`}>{children}</body>
    </html>
  );
}
